### ISSUE TITLE
"overflow: auto" for .col?

### ISSUE THREAD

**Issue by jonioni** [alecrios/core#4]
It's a bit annoying that content in the left col may overlap those in the right for text decoration libraries(e.g., KaTeX) that modifies the original text flow. So perhaps a simple overflow setting could be added?

**Comment by alecrios** [comment]
@jonioni This is a specific case which I don't think would be necessary on most projects. I'd say it falls outside the scope of a general reset and grid system, so I'm going to close this issue.
